//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierGenikiTaxydromiki
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx", ConfigurationName="CourierGenikiTaxydromiki.JobServicesSoap")]
    public interface JobServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.AuthenticateResult> AuthenticateAsync(string sUsrName, string sUsrPwd, string applicationKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/ClosePendingJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> ClosePendingJobsAsync(string sAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/CreateJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CreateJobResult> CreateJobAsync(string sAuthKey, CourierGenikiTaxydromiki.Record oVoucher, CourierGenikiTaxydromiki.JobType eType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/AddJobReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> AddJobReportAsync(string sAuthKey, long nJobId, string sOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetVoucherJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetVoucherJobResult> GetVoucherJobAsync(string sAuthKey, long nJobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/ClosePendingJobsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> ClosePendingJobsByDateAsync(string sAuthKey, System.DateTime dFr, System.DateTime dTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/CancelJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> CancelJobAsync(string sAuthKey, long nJobId, bool bCancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/CancelAndCloseJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> CancelAndCloseJobAsync(string authKey, long jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetJobsFromOrderId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetJobsResult> GetJobsFromOrderIdAsync(string sAuthKey, string sOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetJobsResult> GetJobsAsync(string sAuthKey, CourierGenikiTaxydromiki.QueryParameters oParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/TrackAndTrace", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.TrackAndTraceResult> TrackAndTraceAsync(string authKey, string voucherNo, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> ChangePasswordAsync(string authKey, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetVoucherPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task GetVoucherPdfAsync(string authKey, string voucherNo, CourierGenikiTaxydromiki.MediaFormat format, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetVouchersPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task GetVouchersPdfAsync(string authKey, string[] voucherNumbers, CourierGenikiTaxydromiki.MediaFormat format, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/AddExtraInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> AddExtraInfoAsync(string authKey, long jobId, string extraInfo, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/GetShopsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetShopsResult> GetShopsListAsync(string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/CalculateCost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CalculateCostResult> CalculateCostAsync(string authKey, int routeId, decimal weight, string[] services);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/CalculateDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CalculateDayResult> CalculateDayAsync(string authKey, int regionFromId, int regionToId, System.DateTime receivedOn, CourierGenikiTaxydromiki.ShipmentType shipmentType, bool deliverOnSaturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/Helper", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<object> HelperAsync(string paramName, object[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://voucher.taxydromiki.gr/JobServices.asmx/Echo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseJob))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MethodResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> EchoAsync(int value);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class AuthenticateResult : MethodResult
    {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculateDayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculateCostResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetShopsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackAndTraceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobMethodResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVoucherJobResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateJobResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticateResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class MethodResult
    {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class QueryParameters
    {
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        private string voucherNumberField;
        
        private string consigneeNameField;
        
        private string orderIdField;
        
        private string userNameField;
        
        private VoucherState stateField;
        
        private CountType counTypeField;
        
        private SearchType searchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VoucherNumber
        {
            get
            {
                return this.voucherNumberField;
            }
            set
            {
                this.voucherNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }
            set
            {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public VoucherState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CountType CounType
        {
            get
            {
                return this.counTypeField;
            }
            set
            {
                this.counTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public SearchType SearchType
        {
            get
            {
                return this.searchTypeField;
            }
            set
            {
                this.searchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum VoucherState
    {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        ClosedActive,
        
        /// <remarks/>
        ClosedCanceled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum CountType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        JobsOnly,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum SearchType
    {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        Vouchers,
        
        /// <remarks/>
        Orders,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class Shop
    {
        
        private string codeField;
        
        private string code2Field;
        
        private string nameField;
        
        private string stateField;
        
        private string cityField;
        
        private string addressField;
        
        private string telephoneField;
        
        private string zipField;
        
        private string emailField;
        
        private string countryField;
        
        private decimal longitudeField;
        
        private decimal latitudeField;
        
        private bool subShopField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code2
        {
            get
            {
                return this.code2Field;
            }
            set
            {
                this.code2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool SubShop
        {
            get
            {
                return this.subShopField;
            }
            set
            {
                this.subShopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class Checkpoint
    {
        
        private string statusField;
        
        private System.DateTime statusDateField;
        
        private string shopField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StatusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Shop
        {
            get
            {
                return this.shopField;
            }
            set
            {
                this.shopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoucherJob))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class BaseJob
    {
        
        private long idField;
        
        private JobType typeField;
        
        private string orderIdField;
        
        private System.DateTime dateField;
        
        private string userField;
        
        private bool isClosedField;
        
        private bool isCanceledField;
        
        private string statusField;
        
        private System.DateTime statusDateField;
        
        private int closingBatchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public JobType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsClosed
        {
            get
            {
                return this.isClosedField;
            }
            set
            {
                this.isClosedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsCanceled
        {
            get
            {
                return this.isCanceledField;
            }
            set
            {
                this.isCanceledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime StatusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ClosingBatch
        {
            get
            {
                return this.closingBatchField;
            }
            set
            {
                this.closingBatchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum JobType
    {
        
        /// <remarks/>
        Voucher,
        
        /// <remarks/>
        Pickup,
        
        /// <remarks/>
        SendAndReturn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class VoucherJob : BaseJob
    {
        
        private Record voucherField;
        
        private Record returningVoucherField;
        
        private Record[] subVouchersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Record Voucher
        {
            get
            {
                return this.voucherField;
            }
            set
            {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Record ReturningVoucher
        {
            get
            {
                return this.returningVoucherField;
            }
            set
            {
                this.returningVoucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Record[] SubVouchers
        {
            get
            {
                return this.subVouchersField;
            }
            set
            {
                this.subVouchersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class Record
    {
        
        private string orderIdField;
        
        private string nameField;
        
        private string addressField;
        
        private string emailField;
        
        private string countryField;
        
        private string countryIsoField;
        
        private string cityField;
        
        private string telephoneField;
        
        private string zipField;
        
        private string destinationField;
        
        private string courierField;
        
        private int piecesField;
        
        private decimal weightField;
        
        private string commentsField;
        
        private string servicesField;
        
        private decimal codAmountField;
        
        private decimal insAmountField;
        
        private string voucherNoField;
        
        private string subCodeField;
        
        private string belongsToField;
        
        private string deliverToField;
        
        private System.DateTime receivedDateField;
        
        private string contentsDescriptionField;
        
        private string sendAndReturnRecipientField;
        
        private string extraInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryIso
        {
            get
            {
                return this.countryIsoField;
            }
            set
            {
                this.countryIsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Courier
        {
            get
            {
                return this.courierField;
            }
            set
            {
                this.courierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Pieces
        {
            get
            {
                return this.piecesField;
            }
            set
            {
                this.piecesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal CodAmount
        {
            get
            {
                return this.codAmountField;
            }
            set
            {
                this.codAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal InsAmount
        {
            get
            {
                return this.insAmountField;
            }
            set
            {
                this.insAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string VoucherNo
        {
            get
            {
                return this.voucherNoField;
            }
            set
            {
                this.voucherNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SubCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string BelongsTo
        {
            get
            {
                return this.belongsToField;
            }
            set
            {
                this.belongsToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DeliverTo
        {
            get
            {
                return this.deliverToField;
            }
            set
            {
                this.deliverToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime ReceivedDate
        {
            get
            {
                return this.receivedDateField;
            }
            set
            {
                this.receivedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ContentsDescription
        {
            get
            {
                return this.contentsDescriptionField;
            }
            set
            {
                this.contentsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string SendAndReturnRecipient
        {
            get
            {
                return this.sendAndReturnRecipientField;
            }
            set
            {
                this.sendAndReturnRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class CalculateDayResult : MethodResult
    {
        
        private int minDaysField;
        
        private int maxDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MinDays
        {
            get
            {
                return this.minDaysField;
            }
            set
            {
                this.minDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxDays
        {
            get
            {
                return this.maxDaysField;
            }
            set
            {
                this.maxDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class CalculateCostResult : MethodResult
    {
        
        private decimal costField;
        
        private decimal vatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class GetShopsResult : MethodResult
    {
        
        private Shop[] shopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Shop[] Shops
        {
            get
            {
                return this.shopsField;
            }
            set
            {
                this.shopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class TrackAndTraceResult : MethodResult
    {
        
        private Checkpoint[] checkpointsField;
        
        private string statusField;
        
        private System.DateTime deliveryDateField;
        
        private string consigneeField;
        
        private string returningServiceVoucherField;
        
        private string deliveredAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Checkpoint[] Checkpoints
        {
            get
            {
                return this.checkpointsField;
            }
            set
            {
                this.checkpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReturningServiceVoucher
        {
            get
            {
                return this.returningServiceVoucherField;
            }
            set
            {
                this.returningServiceVoucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DeliveredAt
        {
            get
            {
                return this.deliveredAtField;
            }
            set
            {
                this.deliveredAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class GetJobsResult : MethodResult
    {
        
        private VoucherJob[] jobsField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public VoucherJob[] Jobs
        {
            get
            {
                return this.jobsField;
            }
            set
            {
                this.jobsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVoucherJobResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateJobResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class JobMethodResult : MethodResult
    {
        
        private long jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long JobId
        {
            get
            {
                return this.jobIdField;
            }
            set
            {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class GetVoucherJobResult : JobMethodResult
    {
        
        private VoucherJob jobField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VoucherJob Job
        {
            get
            {
                return this.jobField;
            }
            set
            {
                this.jobField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public partial class CreateJobResult : JobMethodResult
    {
        
        private string voucherField;
        
        private Record[] subVouchersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Voucher
        {
            get
            {
                return this.voucherField;
            }
            set
            {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Record[] SubVouchers
        {
            get
            {
                return this.subVouchersField;
            }
            set
            {
                this.subVouchersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum MediaFormat
    {
        
        /// <remarks/>
        Sticker,
        
        /// <remarks/>
        Flyer,
        
        /// <remarks/>
        StickerF6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum ExtraInfoFormat
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        ThreeW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://voucher.taxydromiki.gr/JobServices.asmx")]
    public enum ShipmentType
    {
        
        /// <remarks/>
        MailOrPackageLess2Kg,
        
        /// <remarks/>
        PackageMore2Kg,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface JobServicesSoapChannel : CourierGenikiTaxydromiki.JobServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class JobServicesSoapClient : System.ServiceModel.ClientBase<CourierGenikiTaxydromiki.JobServicesSoap>, CourierGenikiTaxydromiki.JobServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JobServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(JobServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), JobServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JobServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JobServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.AuthenticateResult> AuthenticateAsync(string sUsrName, string sUsrPwd, string applicationKey)
        {
            return base.Channel.AuthenticateAsync(sUsrName, sUsrPwd, applicationKey);
        }
        
        public System.Threading.Tasks.Task<int> ClosePendingJobsAsync(string sAuthKey)
        {
            return base.Channel.ClosePendingJobsAsync(sAuthKey);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CreateJobResult> CreateJobAsync(string sAuthKey, CourierGenikiTaxydromiki.Record oVoucher, CourierGenikiTaxydromiki.JobType eType)
        {
            return base.Channel.CreateJobAsync(sAuthKey, oVoucher, eType);
        }
        
        public System.Threading.Tasks.Task<int> AddJobReportAsync(string sAuthKey, long nJobId, string sOrderId)
        {
            return base.Channel.AddJobReportAsync(sAuthKey, nJobId, sOrderId);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetVoucherJobResult> GetVoucherJobAsync(string sAuthKey, long nJobId)
        {
            return base.Channel.GetVoucherJobAsync(sAuthKey, nJobId);
        }
        
        public System.Threading.Tasks.Task<int> ClosePendingJobsByDateAsync(string sAuthKey, System.DateTime dFr, System.DateTime dTo)
        {
            return base.Channel.ClosePendingJobsByDateAsync(sAuthKey, dFr, dTo);
        }
        
        public System.Threading.Tasks.Task<int> CancelJobAsync(string sAuthKey, long nJobId, bool bCancel)
        {
            return base.Channel.CancelJobAsync(sAuthKey, nJobId, bCancel);
        }
        
        public System.Threading.Tasks.Task<int> CancelAndCloseJobAsync(string authKey, long jobId)
        {
            return base.Channel.CancelAndCloseJobAsync(authKey, jobId);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetJobsResult> GetJobsFromOrderIdAsync(string sAuthKey, string sOrderId)
        {
            return base.Channel.GetJobsFromOrderIdAsync(sAuthKey, sOrderId);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetJobsResult> GetJobsAsync(string sAuthKey, CourierGenikiTaxydromiki.QueryParameters oParams)
        {
            return base.Channel.GetJobsAsync(sAuthKey, oParams);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.TrackAndTraceResult> TrackAndTraceAsync(string authKey, string voucherNo, string language)
        {
            return base.Channel.TrackAndTraceAsync(authKey, voucherNo, language);
        }
        
        public System.Threading.Tasks.Task<int> ChangePasswordAsync(string authKey, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(authKey, newPassword);
        }
        
        public System.Threading.Tasks.Task GetVoucherPdfAsync(string authKey, string voucherNo, CourierGenikiTaxydromiki.MediaFormat format, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat)
        {
            return base.Channel.GetVoucherPdfAsync(authKey, voucherNo, format, extraInfoFormat);
        }
        
        public System.Threading.Tasks.Task GetVouchersPdfAsync(string authKey, string[] voucherNumbers, CourierGenikiTaxydromiki.MediaFormat format, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat)
        {
            return base.Channel.GetVouchersPdfAsync(authKey, voucherNumbers, format, extraInfoFormat);
        }
        
        public System.Threading.Tasks.Task<int> AddExtraInfoAsync(string authKey, long jobId, string extraInfo, CourierGenikiTaxydromiki.ExtraInfoFormat extraInfoFormat)
        {
            return base.Channel.AddExtraInfoAsync(authKey, jobId, extraInfo, extraInfoFormat);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.GetShopsResult> GetShopsListAsync(string authKey)
        {
            return base.Channel.GetShopsListAsync(authKey);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CalculateCostResult> CalculateCostAsync(string authKey, int routeId, decimal weight, string[] services)
        {
            return base.Channel.CalculateCostAsync(authKey, routeId, weight, services);
        }
        
        public System.Threading.Tasks.Task<CourierGenikiTaxydromiki.CalculateDayResult> CalculateDayAsync(string authKey, int regionFromId, int regionToId, System.DateTime receivedOn, CourierGenikiTaxydromiki.ShipmentType shipmentType, bool deliverOnSaturday)
        {
            return base.Channel.CalculateDayAsync(authKey, regionFromId, regionToId, receivedOn, shipmentType, deliverOnSaturday);
        }
        
        public System.Threading.Tasks.Task<object> HelperAsync(string paramName, object[] parameters)
        {
            return base.Channel.HelperAsync(paramName, parameters);
        }
        
        public System.Threading.Tasks.Task<int> EchoAsync(int value)
        {
            return base.Channel.EchoAsync(value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JobServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.JobServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JobServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://testvoucher.taxydromiki.gr/JobServices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.JobServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://testvoucher.taxydromiki.gr/JobServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            JobServicesSoap,
            
            JobServicesSoap12,
        }
    }
}
